/* ============================================================
   JD -> LaTeX Resume Matcher — src/latex.js  (Phase 3)
   LaTeX generation engine.

   Three responsibilities:
     1. TEX_TEMPLATE  — a self-contained "Jake's Resume"-style
        template string with {{PLACEHOLDER}} tags.
     2. escapeLatex() — turn LLM/user text into LaTeX-safe text so
        reserved characters (& % $ # _ { } ~ ^ \) don't crash the
        compiler.
     3. generateLatexResume() — inject sanitized TailoredResumeData
        into the template and return a complete, compilable .tex string.

   The template is intentionally self-contained (no external .cls) so
   it compiles on Overleaf or any full TeX Live install as-is.
   ============================================================ */
"use strict";

const { str, toTailoredResumeData } = require("./models");

/* ============================================================
   1. ESCAPING
   ============================================================ */

// Single-pass map. JavaScript's String.replace scans the ORIGINAL string
// once and never re-scans replacement text, so the braces/backslashes we
// introduce here are safe and never double-escaped.
const LATEX_ESCAPES = {
  "\\": "\\textbackslash{}",
  "{": "\\{",
  "}": "\\}",
  "&": "\\&",
  "%": "\\%",
  "$": "\\$",
  "#": "\\#",
  "_": "\\_",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
};

/**
 * Escape a string for use as ordinary LaTeX body text.
 * e.g. "Backend & Frontend" -> "Backend \& Frontend"
 *      "my_database_project" -> "my\_database\_project"
 *
 * @param {unknown} input
 * @returns {string}
 */
function escapeLatex(input) {
  return str(input).replace(/[\\{}&%$#_~^]/g, (ch) => LATEX_ESCAPES[ch]);
}

// In a \href{URL}{...} the URL argument tolerates more than body text, but
// these characters are still fatal and must be escaped. We deliberately
// leave `_`, `~`, `/`, `:` alone (legal/normal in URLs).
const URL_ESCAPES = { "\\": "\\textbackslash{}", "{": "\\{", "}": "\\}", "%": "\\%", "#": "\\#", "&": "\\&" };

/** Escape a URL for the first argument of \href. */
function escapeLatexUrl(input) {
  return str(input).replace(/[\\{}%#&]/g, (ch) => URL_ESCAPES[ch]);
}

/** Add https:// if a URL has no scheme (so links are clickable). */
function withScheme(url) {
  const u = str(url);
  if (!u) return "";
  return /^[a-z][a-z0-9+.-]*:\/\//i.test(u) || u.startsWith("mailto:") ? u : "https://" + u;
}

/* ============================================================
   2. TEMPLATES  (String.raw => backslashes stay literal)
   ============================================================ */

const TEX_TEMPLATE = String.raw`%% Generated by DevFolio JD->LaTeX Resume Matcher.
%% Jake's-Resume-style, self-contained (compiles on Overleaf / TeX Live).
\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{\vspace{-4pt}\scshape\raggedright\large}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

%% Ensure the PDF is machine-readable (ATS-friendly).
\pdfgentounicode=1

%% Custom commands
\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}
\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}
\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}

%% Heading
\begin{center}
    \textbf{\Huge \scshape {{NAME}}} \\ \vspace{1pt}
    \small {{CONTACT}}
\end{center}

%% Education
\section{Education}
  \resumeSubHeadingListStart
{{EDUCATION}}
  \resumeSubHeadingListEnd

%% Skills
\section{Technical Skills}
 \begin{itemize}[leftmargin=0.15in, label={}]
    \small{\item{
{{SKILLS}}
    }}
 \end{itemize}

%% Projects
\section{Projects}
    \resumeSubHeadingListStart
{{PROJECTS}}
    \resumeSubHeadingListEnd

\end{document}
`;

const EDUCATION_ENTRY = String.raw`    \resumeSubheading{{{COLLEGE}}}{{{GRAD_YEAR}}}{{{DEGREE}}}{{{GPA}}}`;

const PROJECT_ENTRY = String.raw`    \resumeProjectHeading
      {\textbf{{{PROJECT_NAME}}} $|$ \emph{{{PROJECT_TECH}}}}{}
      \resumeItemListStart
{{PROJECT_BULLETS}}
      \resumeItemListEnd`;

const PROJECT_BULLET = String.raw`        \resumeItem{{{BULLET}}}`;

/* ============================================================
   3. INJECTION
   ============================================================ */

/**
 * Replace each {{KEY}} with its value via split/join (NOT String.replace,
 * whose replacement string would interpret `$` — fatal for LaTeX math).
 *
 * @param {string} template
 * @param {Record<string, string>} values
 * @returns {string}
 */
function injectTemplate(template, values) {
  let out = template;
  for (const [key, value] of Object.entries(values)) {
    out = out.split(`{{${key}}}`).join(value);
  }
  return out;
}

/* -------- section builders -------- */

/** Build the centered contact line ("a $|$ b $|$ c") from ContactInfo. */
function buildContactLine(contact) {
  const c = contact || {};
  const items = [];

  if (c.phone) items.push(escapeLatex(c.phone));
  if (c.email) items.push(`\\href{mailto:${escapeLatexUrl(c.email)}}{${escapeLatex(c.email)}}`);

  const link = (raw, label) => {
    const url = withScheme(raw);
    if (!url) return null;
    return `\\href{${escapeLatexUrl(url)}}{${escapeLatex(label)}}`;
  };
  const linkedin = link(c.linkedin, displayUrl(c.linkedin) || "LinkedIn");
  const github = link(c.github, displayUrl(c.github) || "GitHub");
  const portfolio = link(c.portfolio, displayUrl(c.portfolio) || "Portfolio");
  for (const it of [linkedin, github, portfolio]) if (it) items.push(it);

  return items.join(" $|$ ");
}

/** Human-readable link label: strip scheme + trailing slash. */
function displayUrl(raw) {
  return str(raw).replace(/^[a-z]+:\/\//i, "").replace(/\/+$/, "");
}

/** Build the Education entry from EducationInfo (or "" if empty). */
function buildEducation(edu) {
  const e = edu || {};
  if (!e.college && !e.degree) return "";
  const gpa = e.gpa ? `GPA: ${escapeLatex(e.gpa)}` : "";
  return injectTemplate(EDUCATION_ENTRY, {
    COLLEGE: escapeLatex(e.college || "—"),
    GRAD_YEAR: escapeLatex(e.graduationYear || ""),
    DEGREE: escapeLatex(e.degree || ""),
    GPA: gpa,
  });
}

/** Build the skills line. Falls back to the union of project techs. */
function buildSkills(data) {
  let skills = data.matchedSkills;
  if (!skills || !skills.length) {
    const set = new Set();
    for (const p of data.selectedProjects) for (const t of p.technologies) set.add(t);
    skills = [...set];
  }
  if (!skills.length) return "     \\textit{See projects below.}";
  return `     \\textbf{Skills}{: ${escapeLatex(skills.join(", "))}}`;
}

/** Build one project entry (heading + bullet list). */
function buildProject(p) {
  const tech = p.technologies.length ? p.technologies.join(", ") : "—";
  const bullets = (p.tailoredBullets.length ? p.tailoredBullets : [p.description].filter(Boolean))
    .map((b) => injectTemplate(PROJECT_BULLET, { BULLET: escapeLatex(b) }))
    .join("\n");

  return injectTemplate(PROJECT_ENTRY, {
    PROJECT_NAME: escapeLatex(p.name),
    PROJECT_TECH: escapeLatex(tech),
    PROJECT_BULLETS: bullets,
  });
}

/* ============================================================
   PHASE 3 ENTRY POINT
   ============================================================ */

/**
 * Generate a complete, compilable .tex document from resume data.
 * Input is normalized first so partial data never produces broken LaTeX.
 *
 * @param {Partial<import('./models').TailoredResumeData>} resumeData
 * @returns {string} full LaTeX source
 */
function generateLatexResume(resumeData) {
  const data = toTailoredResumeData(resumeData);

  return injectTemplate(TEX_TEMPLATE, {
    NAME: escapeLatex(data.name || "Your Name"),
    CONTACT: buildContactLine(data.contactInfo),
    EDUCATION: buildEducation(data.education),
    SKILLS: buildSkills(data),
    PROJECTS: data.selectedProjects.map(buildProject).join("\n"),
  });
}

module.exports = {
  escapeLatex,
  escapeLatexUrl,
  generateLatexResume,
  buildContactLine,
  TEX_TEMPLATE,
};
